// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jceggjtlmvaocivekhba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZWdnanRsbXZhb2NpdmVraGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzkzNjksImV4cCI6MjA2NTE1NTM2OX0.itkE71TeF1m3tqRRd0Zgsth0tkfRqS1e2RqbJL-OTZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);